# Generated by Django 3.1.1 on 2020-10-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Группа')),
                ('location', models.TextField(blank=True, verbose_name='Расположение')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=64, null=True, verbose_name='должность')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='приоритет')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='РЭС')),
                ('short_name', models.CharField(max_length=16, unique=True, verbose_name='РЭС сокращ + участок')),
                ('location', models.TextField(blank=True, verbose_name='Расположение')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
            ],
            options={
                'verbose_name': 'РЭС',
                'verbose_name_plural': 'РЭСы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название организации')),
                ('short_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Назв орган сокращ')),
                ('ours', models.BooleanField(verbose_name='наши')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер ПС')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название ПС')),
                ('voltage_h', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='напряжение высокое')),
                ('voltage_m', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='напряжение среднее')),
                ('voltage_l', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='напряжение низкое')),
                ('alien', models.BooleanField(verbose_name='абонентская?')),
                ('location', models.TextField(blank=True, verbose_name='Расположение')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substations', to='tula_net.group', verbose_name='Группа')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substations', to='tula_net.subscriber', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Подстанция',
                'verbose_name_plural': 'Подстанции',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название секции')),
                ('voltage', models.PositiveSmallIntegerField(verbose_name='напряжение')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tula_net.substation')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='номер')),
                ('mail', models.EmailField(blank=True, max_length=32, verbose_name='электронка')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='приоритет')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='tula_net.person')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='tula_net.subscriber')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='tula_net.subscriber'),
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название фидера')),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протяженность')),
                ('number_tp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество ТП')),
                ('population', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Население')),
                ('social', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Социалка')),
                ('attention', models.BooleanField(verbose_name='!!!')),
                ('reliability_category', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='категория надежности')),
                ('in_reserve', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
                ('res', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='tula_net.res', verbose_name='РЭС или еще кто')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='tula_net.section', verbose_name='СкШ')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='tula_net.subscriber', verbose_name='абонент')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='tula_net.substation', verbose_name='ПС')),
            ],
            options={
                'verbose_name': 'фидер',
                'verbose_name_plural': 'фидера',
                'ordering': ['section', 'name'],
            },
        ),
    ]
