# Generated by Django 3.1.1 on 2020-10-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder_characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_name', models.CharField(max_length=64, verbose_name='Название фидера')),
                ('substation_name', models.CharField(max_length=64, verbose_name='Название ПС')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Протяженность')),
                ('tp_our_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ТП наши: количество')),
                ('tp_alien_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ТП чужие: количество')),
                ('villages_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='НП количество')),
                ('villages_names', models.TextField(blank=True, null=True, verbose_name='НП названия')),
                ('power_winter', models.FloatField(blank=True, null=True, verbose_name='Зима МВт')),
                ('power_summer', models.FloatField(blank=True, null=True, verbose_name='Лето МВт')),
                ('population', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Население')),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Точки поставки')),
                ('social_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Социалка кол-во')),
                ('social_names', models.TextField(blank=True, null=True, verbose_name='Социалка тип')),
                ('feeder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character', to='tula_net.feeder', verbose_name='фидер')),
            ],
            options={
                'verbose_name': 'характеристика фидера',
                'verbose_name_plural': 'х-ки фидеров',
                'unique_together': {('feeder_name', 'substation_name')},
            },
        ),
    ]
