# Generated by Django 3.1.1 on 2020-10-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='short_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='РЭС сокращ + участок'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название организации'),
        ),
    ]
