# Generated by Django 3.1.1 on 2020-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['voltage__class_voltage', 'name'], 'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterField(
            model_name='feeder',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название фидера'),
        ),
    ]
