# Generated by Django 3.1.1 on 2020-10-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ours',
            field=models.BooleanField(blank=True, null=True, verbose_name='наши'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описение'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='in_reserve',
            field=models.BooleanField(default=False, verbose_name='Резервный'),
        ),
    ]
