# Generated by Django 3.1.1 on 2020-10-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, default='', max_length=32, verbose_name='Цифровое название')),
                ('ps_p1', models.PositiveSmallIntegerField(verbose_name='Номер 1-й питающей ПС')),
                ('sec_p1', models.PositiveSmallIntegerField(verbose_name='Номер 1-й питающей СкШ/СШ')),
                ('ps_p2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 2-й питающей ПС')),
                ('sec_p2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 1-й питающей СкШ/СШ')),
                ('ps_m1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 1-й тупиковой ПС')),
                ('sec_m1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 1-й тупиковой СкШ/СШ')),
                ('ps_m2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 2-й тупиковой ПС')),
                ('sec_m2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 2-й тупиковой СкШ/СШ')),
                ('ps_m3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 3-й тупиковой ПС')),
                ('sec_m3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 3-й тупиковой СкШ/СШ')),
                ('ps_m4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 4-й тупиковой ПС')),
                ('sec_m4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер 4-й тупиковой СкШ/СШ')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Протяженность')),
                ('number_columns', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество опор')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описение')),
                ('kvl', models.BooleanField(default=False, verbose_name='КВЛ?')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tula_net.groupline', verbose_name='Участок сл ВЛ')),
                ('maintenance', models.ManyToManyField(blank=True, related_name='lines_ved1', to='tula_net.Region', verbose_name='Ведение')),
                ('management', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lines_upr1', to='tula_net.region', verbose_name='Управление')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='tula_net.subscriber', verbose_name='абонент')),
                ('voltage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='tula_net.classvoltage', verbose_name='Напряжение')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['voltage', 'short_name'],
            },
        ),
    ]
