# Generated by Django 3.1.1 on 2020-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0002_auto_20201007_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeder',
            options={'ordering': ['section', 'subscriber', 'name'], 'verbose_name': 'фидер', 'verbose_name_plural': 'фидера'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-ours', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-ours', 'name'], 'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='year_update',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Списки обновлены'),
        ),
    ]
