# Generated by Django 3.1.1 on 2020-10-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0002_auto_20201016_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регион',
            },
        ),
        migrations.CreateModel(
            name='TransmissionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Цифровое название')),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протяженность')),
                ('number_columns', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество опор')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описение')),
                ('kvl', models.BooleanField(default=False, verbose_name='КВЛ?')),
                ('maintenance', models.ManyToManyField(blank=True, related_name='lines_ved', to='tula_net.Region', verbose_name='Ведение')),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_upr', to='tula_net.region', verbose_name='Управление')),
                ('section', models.ManyToManyField(related_name='lines', to='tula_net.Section', verbose_name='Секция')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='tula_net.subscriber', verbose_name='абонент')),
                ('substation', models.ManyToManyField(related_name='lines', to='tula_net.Substation', verbose_name='ПС')),
                ('voltage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='tula_net.classvoltage', verbose_name='Напряжение')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['voltage', 'management'],
            },
        ),
    ]
