# Generated by Django 3.1.1 on 2020-10-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0002_feeder_characteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeder',
            name='length',
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='number_tp',
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='points',
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='population',
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='res',
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='social',
        ),
        migrations.AddField(
            model_name='feeder_characteristic',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='соответствует'),
        ),
    ]
