# Generated by Django 3.1.1 on 2020-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0002_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='mail',
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='№ секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='from_T',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='питается от/питает Т №'),
        ),
    ]
