# Generated by Django 3.1.1 on 2020-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0003_auto_20201008_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='search_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='номер'),
        ),
    ]
