# Generated by Django 3.1.1 on 2020-10-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0003_region_transmissionline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeder',
            name='region',
        ),
        migrations.RemoveField(
            model_name='substation',
            name='region',
        ),
    ]
