# Generated by Django 3.1.1 on 2020-10-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0004_phone_search_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='tula_net.substation'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='search_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='НЕ ЗАПОЛНЯТЬ'),
        ),
    ]
