# Generated by Django 3.1.1 on 2020-10-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0004_auto_20201017_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='tula_net.region', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='substation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substations', to='tula_net.region', verbose_name='Участок'),
        ),
    ]
