# Generated by Django 3.1.1 on 2020-10-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0005_auto_20201008_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, verbose_name='описение'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='tula_net.person', verbose_name='лицо'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='tula_net.subscriber', verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='tula_net.substation', verbose_name='ПС'),
        ),
    ]
