# Generated by Django 3.1.1 on 2020-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0005_auto_20201017_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='blind',
            field=models.BooleanField(default=True, verbose_name='Тупиковая'),
        ),
    ]
