# Generated by Django 3.1.1 on 2020-10-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0006_section_blind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Группа')),
                ('location', models.TextField(blank=True, verbose_name='Расположение')),
                ('description', models.TextField(blank=True, verbose_name='Описение')),
                ('ours', models.BooleanField(blank=True, null=True, verbose_name='наши')),
            ],
            options={
                'verbose_name': 'Участок сл ВЛ',
                'verbose_name_plural': 'Участки сл ВЛ',
                'ordering': ['-ours', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transmissionline',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='tula_net.groupline', verbose_name='Участок сл ВЛ'),
        ),
    ]
