# Generated by Django 3.1.1 on 2020-10-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0006_auto_20201012_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='tula_net.section', verbose_name='СкШ'),
        ),
    ]
