# Generated by Django 3.1.1 on 2020-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0008_auto_20201012_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVoltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_voltage', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Класс напряжения')),
            ],
            options={
                'verbose_name': 'напряжение',
                'verbose_name_plural': 'напряжения',
                'ordering': ['-class_voltage'],
            },
        ),
    ]
