# Generated by Django 3.1.1 on 2020-10-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0008_auto_20201018_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='for_menu',
            field=models.BooleanField(default=False, verbose_name='Добавить в меню'),
        ),
        migrations.AlterField(
            model_name='section',
            name='blind',
            field=models.BooleanField(default=False, verbose_name='Тупиковая'),
        ),
    ]
