# Generated by Django 3.1.1 on 2020-10-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0009_auto_20201018_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmissionline',
            name='substation',
        ),
    ]
