# Generated by Django 3.1.1 on 2020-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0009_classvoltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classvoltage',
            name='class_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Класс напряжения'),
        ),
    ]
