# Generated by Django 3.1.1 on 2020-10-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0010_remove_transmissionline_substation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissionline',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tula_net.groupline', verbose_name='Участок сл ВЛ'),
        ),
        migrations.AlterField(
            model_name='transmissionline',
            name='management',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines_upr', to='tula_net.region', verbose_name='Управление'),
        ),
    ]
