# Generated by Django 3.1.1 on 2020-10-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0010_auto_20201016_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='volt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tula_net.classvoltage', verbose_name='напряжение'),
        ),
    ]
