# Generated by Django 3.1.1 on 2020-10-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0011_auto_20201018_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissionline',
            name='management',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lines_upr', to='tula_net.region', verbose_name='Управление'),
        ),
    ]
