# Generated by Django 3.1.1 on 2020-10-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0011_section_volt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classvoltage',
            name='class_voltage',
            field=models.SmallIntegerField(verbose_name='Класс напряжения'),
        ),
    ]
