# Generated by Django 3.1.1 on 2020-10-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0012_auto_20201016_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='voltage',
        ),
    ]
