# Generated by Django 3.1.1 on 2020-10-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0012_auto_20201018_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='transmissionline',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Протяженность'),
        ),
    ]
