# Generated by Django 3.1.1 on 2020-10-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0013_remove_section_voltage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='volt',
            new_name='voltage',
        ),
    ]
