# Generated by Django 3.1.1 on 2020-10-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0014_auto_20201016_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substation',
            name='voltage_h',
        ),
        migrations.RemoveField(
            model_name='substation',
            name='voltage_l',
        ),
        migrations.RemoveField(
            model_name='substation',
            name='voltage_m',
        ),
    ]
