# Generated by Django 3.1.1 on 2020-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0014_feeder_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-priority'], 'verbose_name': 'Ответственное лицо', 'verbose_name_plural': 'Ответственные лица'},
        ),
        migrations.AlterField(
            model_name='transmissionline',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Цифровое название'),
        ),
    ]
