# Generated by Django 3.1.1 on 2020-10-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0015_auto_20201016_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='voltage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tula_net.classvoltage', verbose_name='напряжение'),
        ),
    ]
