# Generated by Django 3.1.1 on 2020-10-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0016_auto_20201016_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='voltage_h',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_volt_h', to='tula_net.classvoltage', verbose_name='напряжение высокое'),
        ),
        migrations.AddField(
            model_name='substation',
            name='voltage_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_volt_l', to='tula_net.classvoltage', verbose_name='напряжение низкое'),
        ),
        migrations.AddField(
            model_name='substation',
            name='voltage_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ps_volt_m', to='tula_net.classvoltage', verbose_name='напряжение среднее'),
        ),
    ]
