# Generated by Django 3.1.1 on 2020-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tula_net', '0017_auto_20201016_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeder',
            options={'ordering': ['section', '-subscriber', 'name'], 'verbose_name': 'фидер', 'verbose_name_plural': 'фидера'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название организации'),
        ),
    ]
